/*
 * This source file was generated by the Gradle 'init' task
 */
package org.simulation.actors;

import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import akka.actor.Props;

public class Main {

    public static void main(String[] args) {
        int numCar = 10;
        int numStep = 100;
        final ActorSystem system = ActorSystem.create("TrafficSimulation");
        system.actorOf(Props.create(CounterActor.class, numCar), "counter");
        system.actorOf(Props.create(EnvironmentActor.class, numCar, numStep), "env");
        //system.actorSelection("/user/env").tell(new Message<Integer>("step", 0), ActorRef.noSender());
    }
}
